# Generated by Django 4.2.1 on 2023-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('class_name', models.CharField(max_length=5)),
                ('grade', models.CharField(max_length=1)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
